name: f_popup_menu
description: A custom popup widget
version: 0.0.1
repository: https://github.com/FlippedOvO/FlippedPopupMenu
homepage: https://github.com/FlippedOvO/FlippedPopupMenu

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
